# Generated by Django 3.2.6 on 2021-10-18 03:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("newsletter", "0005_auto_20190918_0122"),
        ("meetings", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="meeting",
            name="announcement_link",
        ),
        migrations.AddField(
            model_name="meeting",
            name="announcement",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="newsletter.message",
            ),
        ),
    ]
