# Generated by Django 3.2.6 on 2021-10-20 00:35

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ("newsletter", "0005_auto_20190918_0122"),
        ("meetings", "0002_auto_20211018_0334"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meeting",
            name="announcement",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="newsletter.submission",
            ),
        ),
        migrations.AlterField(
            model_name="meeting",
            name="meeting_text",
            field=tinymce.models.HTMLField(),
        ),
    ]
