# Generated by Django 3.2.6 on 2021-10-27 00:53

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0004_alter_meeting_announcement'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='short_description',
            field=tinymce.models.HTMLField(default=''),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='meeting_text',
            field=tinymce.models.HTMLField(default=''),
        ),
    ]
