# Generated by Django 3.2.6 on 2021-11-01 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meetings", "0005_auto_20211027_0053"),
    ]

    operations = [
        migrations.AddField(
            model_name="meeting",
            name="no_announcement",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="meeting",
            name="date",
            field=models.DateTimeField(null=True),
        ),
    ]
