# Generated by Django 3.2.6 on 2022-03-21 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("meetings", "0007_auto_20211105_2058"),
    ]

    operations = [
        migrations.RenameField(
            model_name="meeting",
            old_name="no_announcement",
            new_name="tba",
        ),
    ]
