# Generated by Django 3.2.6 on 2022-02-08 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EmailFailure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("raw_message", models.TextField()),
                (
                    "failure_type",
                    models.CharField(
                        choices=[("BO", "Bounce"), ("CO", "Complaint")],
                        default="BO",
                        max_length=2,
                    ),
                ),
            ],
        ),
    ]
