version: '3.7'

services:
  db:
    image: postgres:12.0-alpine
    volumes:
      - princetonpy_postgres_staging:/var/lib/postgresql/data/
    env_file:
      - .env.staging.db
  web:
    build:
      context: ./app
      dockerfile: Dockerfile.prod
    command: hypercorn princetonpy.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./app:/home/app/web
    expose:
      - 8000
    env_file:
      - .env.staging.web
      - .env.staging.aws
    depends_on:
      - db
  caddy:
    image: caddy
    ports:
      - "443:443"
      - "80:80"
    depends_on:
      - web
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./caddy/srv:/srv
      - caddy_data:/data
      - caddy_config:/config

volumes:
  princetonpy_postgres_staging:
    external: true
  caddy_data:
    external: true
  caddy_config: