# Generated by Django 3.1.7 on 2021-07-15 15:08

from django.db import migrations, models
import homepage.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MeetingLink",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "link",
                    models.CharField(
                        blank=True,
                        max_length=300,
                        null=True,
                        validators=[homepage.validators.OptionalSchemeURLValidator],
                    ),
                ),
                ("link_text", models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
    ]
