# Generated by Django 3.2.16 on 2022-11-21 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_alter_meetinglink_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetinglink',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
